name: "Update Modles"

on:
  schedule:
    - cron: "0 13 * * MON"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update models
      run: |
        python fetch-models.py
    - name: Check for changes
      id: changed
      run: |
        git diff --quiet HEAD || echo "::set-output name=has_changed::true"
    - name: Commit changes
      uses: peter-evans/commit-comment@v1
      if: steps.changed.outputs.has_changed == 'true'
      with:
        body: |
          ${{ github.workflow }} has automatically committed changes
        add: .
        commit_message: "Commit changes from GitHub Actions"
